- name: Fail if the password MYSQL_PASSWORD does nor exit
  ansible.builtin.fail:
    msg: MYSQL_PASSWORD variable is missing
  when: MYSQL_PASSWORD is undefined

- name: copy the MYSQL repo file
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install {{COMPONENT}} server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enable: yes

- name: Fetch MYSQL LOg file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
    register: mysql_log

- name: Fetch Password from Mysql log file
  ansible.builtin.set_facts:
    DEFAULT_PASSWORD: "{{mysql_log"

- name: check Mysql password password has been reset or not
  community.mysql.mysql_info:
       login_user: root
       login_password: "{{MYSQL_PASSWORD}}"
        filter: version
  ignore_errors: yes
  register: mysql_conn

- name: Reset MYSQL password
  ansible.builtin.shell: echo "ALTER USER
  when: mysql_conn is failed

- name: check validate password plugin
  ansible.builtin.shell: echo "uninstall plugin validate password;"| mysql -uroot -p"{{MYSQL_PASSWORD}}"
  when: plugin_info is succeeded

- name: remove



