- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import common role for code download {{COMPONENT}} code
  ansible.builtin.inculde_role:
    name: common
    tasks_from: download

- name: copy roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/ngnix/default.d/roboshop.conf

- name: start Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enable: yes
