- name: copy redis yum repos file
  ansible.builtin.template:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo


- name: install redis
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: replace listen address in redis config file
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loops:
    - /etc/redis.conf
    - /etc/redis/redis.conf


- name: start {{COMPONENT}} services
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enable: yes



