#name: download {{COMPONENT}} component archive
 #ansible.builtin.get_url:
   #url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
   #dest: /tmp/{{COMPONENT}}.zip
- name: Create Application user
  ansible.builtin.user:
    name: roboshop

- name: Remove App code
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

- name: Create APP Location
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory

#- name: Download & Extract {{ COMPONENT }} Component Archive
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: copy {{COMPONENT}} code of APP Location
#  ansible.builtin.copy:
#    src: /tmp/{{COMPON|ENT}}-main/{{SUFFIX}}
#    dest: "{{APP_LOCATION}}"
#    remote_src: yes

#- name: Download & Extract {{ COMPONENT }} Component Archive
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: Copy {{ COMPONENT }} Code to App Location
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/{{SUFFIX}}
#    dest: "{{ APP_LOCATION }}/"
#    remote_src: yes

- name: Get Latest Version of Appication from Nexus
  ansible.builtin.shell: curl -s http://nexus.roboshop.internal:8081/service/rest/repository/browse/{{COMPONENT}}/  | grep zip | grep "{{ENV}}-{{COMPONENT}}" | sed -e 's/"/ /g' | xargs -n1 | grep ^http | tail -1
    register: out
  when: APP_VERSION is not defined

- name: Declare URL fact of latest version
  ansible.builtin.set_fact:
    URL: "{{out.stdout}}"
  when: APP_VERSION is not defined

- name: Declare URL fact
  ansible.builtin.set_fact:
    URL: http://nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{ENV}}-{{COMPONENT}}-{{APP_VERSION}}.zip
  when: APP_VERSION is defined

#- name: Download & Extract {{ COMPONENT }} Component Archive from Nexus
#  ansible.builtin.unarchive:
#    src: "{{URL}}"
#    dest: "{{ APP_LOCATION }}"
#    remote_src: yes

#- name: Download & Extract {{ COMPONENT }} Component Archive from Nexus
#  ansible.builtin.unarchive:
#    src: "/tmp/{{COMPONENT}}.zip"
#    dest: "{{ APP_LOCATION }}"
#    remote_src: yes

