#name: download {{COMPONENT}} component archive
 #ansible.builtin.get_url:
   #url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
   #dest: /tmp/{{COMPONENT}}.zip
- name: Create Application user
  ansible.builtin.user:
    name: roboshop

- name: Remove App code
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

- name: Create APP Location
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory

- name: Download & Extract {{ COMPONENT }} Component Archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: copy {{COMPONENT}} code of APP Location
  ansible.builtin.copy:
    src: /tmp/{{COMPON|ENT}}-main/{{SUFFIX}}
    dest: "{{APP_LOCATION}}"
    remote_src: yes

