- name: installl maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Import common App setup configuration
  ansible.builtin.include_role:
    name: common
    task_from: download

- name: install maven dependiences
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar

- name: systemD setup for {{COMPONENT}} service
  ansible.builtin.include_role:
    name: common
    task_from: systemd
