- name: setup the yum repos for nodejs
  ansible.builtin.shell: URL of git repos

- name: install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import common App setup Configuration
  ansible.builtin.include_role:
    name: common
    tasks_from: download

# these steps are now performed from CI steps
#- name: Install NodeJS Dependencies
#  community.general.npm:
#    path: "{{ APP_LOCATION }}"

- name: Copy the configuration file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: started
    enable: yes
    daemon_reload: yes
